# Generated by Django 5.2.8 on 2025-11-08 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inbox_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('work', models.IntegerField(default=0)),
                ('personal', models.IntegerField(default=0)),
                ('promotions', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'date'], name='analytics_d_owner_i_63ae8b_idx')],
                'unique_together': {('owner', 'date')},
            },
        ),
    ]
