# Generated by Django 5.2.8 on 2025-11-08 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_history_id', models.CharField(blank=True, max_length=64)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=128, unique=True)),
                ('thread_id', models.CharField(max_length=128)),
                ('internal_date', models.DateTimeField()),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('label_ids', models.JSONField(default=list)),
                ('direction', models.CharField(max_length=10)),
                ('snippet', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-internal_date'],
                'indexes': [models.Index(fields=['owner', 'internal_date'], name='mail_messag_owner_i_868d4f_idx'), models.Index(fields=['owner', 'direction'], name='mail_messag_owner_i_ced548_idx')],
            },
        ),
    ]
