# Generated by Django 5.2.8 on 2026-01-01 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailMessagePartBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(blank=True, max_length=128)),
                ('size', models.IntegerField(default=0)),
                ('data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=128, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=128)),
                ('label_ids', models.JSONField(default=list)),
                ('snippet', models.CharField(blank=True, max_length=255)),
                ('history_id', models.CharField(blank=True, max_length=64)),
                ('internal_date', models.BigIntegerField()),
                ('size_estimate', models.IntegerField(default=0)),
                ('raw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-internal_date'],
            },
        ),
        migrations.CreateModel(
            name='GmailMessagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(blank=True, max_length=128)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('headers', models.JSONField(default=list)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_parts', to='mail.gmailmessage')),
                ('parent_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='mail.gmailmessagepart')),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_parts', to='mail.gmailmessagepartbody')),
            ],
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mail.gmailmessagepart'),
        ),
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_history_id', models.CharField(blank=True, max_length=64)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=128)),
                ('internal_date', models.DateTimeField(db_index=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('snippet', models.CharField(blank=True, max_length=255)),
                ('label_ids', models.JSONField(default=list)),
                ('direction', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent')], db_index=True, max_length=10)),
                ('has_attachment', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_message', to='mail.gmailmessage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-internal_date'],
            },
        ),
        migrations.AddIndex(
            model_name='gmailmessage',
            index=models.Index(fields=['owner', '-internal_date'], name='mail_gmailm_owner_i_930d18_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailmessage',
            index=models.Index(fields=['thread_id'], name='mail_gmailm_thread__8321de_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['owner', '-internal_date'], name='mail_messag_owner_i_e7309a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['owner', 'direction'], name='mail_messag_owner_i_ced548_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['owner', 'direction', '-internal_date'], name='mail_messag_owner_i_0f9fb7_idx'),
        ),
    ]
